In [565]:
from my_sort import InfinitesimalSort, NaiveInfinitesimalSort
from sort_analyzer import index_from_tresholds
import numpy as np
import pandas as pd
import ipytest 
ipytest.autoconfig()
nan = np.nan

array([nan, nan, nan, nan])

In [586]:
def return_subarray(arr: np.array, n: float):
    tmp = np.append(np.append([0], arr), 1)
    mini = np.argwhere(tmp<n)[-1][0]
    maxi = np.argwhere(tmp>n)[0][0]
    return arr[mini:maxi-1]

In [585]:
%%ipytest
def test_func():
    test = np.array([nan, nan, nan, nan, nan, nan])
    assert np.array_equal(return_subarray(test, 0.3), test, equal_nan=True)
    test = np.array([nan, nan, 0.2, nan, nan, nan])
    resu = np.array([nan, nan, nan])
    assert np.array_equal(return_subarray(test, 0.3), resu, equal_nan=True)
    test = np.array([nan, nan, 0.2, nan, 0.4, nan])
    resu = np.array([nan])
    assert np.array_equal(return_subarray(test, 0.3), resu, equal_nan=True)
    test = np.array([nan, nan, 0.2, nan, 0.4, nan, nan, 0.8])
    resu = np.array([nan, nan])
    assert np.array_equal(return_subarray(test, 0.5), resu, equal_nan=True)

.                                                                                            [100%]
1 passed in 0.02s


In [587]:
def return_subarray(arr: np.array, n: float):
    tmp = np.append(np.append([0], arr), 1)
    mini = np.argwhere(tmp<n)[-1][0]
    maxi = np.argwhere(tmp>n)[0][0]
    return arr[mini:maxi-1], tmp[mini], tmp[maxi]

In [592]:
def best_quasi_sort(arr: np.array, thresholds = None):
    ''' Uses thresholds to sort the array into slots, if slot occupied,'''
    # if not isinstance(np.array, arr):
    arr = np.array(arr)
    n = len(arr)
    slots = np.tile(nan,n)
    if thresholds is None:
        sorti = InfinitesimalSort()
        thresholds = {i: sorti.thresholds(i)[1]  for i in range(n)}
    
    for ni in arr:
        print()
        print(ni)
        print(slots)
        sub, start, end = return_subarray(slots, ni)
        print(sub, start, end)
        if len(sub) == 0:
            raise ValueError('No subarray found, not optimally sortable')
        nip = (ni - start) / (end)      
        idx = index_from_tresholds(thresholds[len(sub)], nip)
        sub[idx] = ni
        print(slots)
    return slots


In [590]:
return_subarray(np.array([nan, nan, 0.2, nan, 0.4, nan, nan, 0.8]), 0.5)

(array([nan, nan]), 0.4, 0.8)

In [595]:
a = [0.51716736, 0.4609964,  0.04710595, 0.5313387,  0.84448939]
best_quasi_sort(a, thresholds)


0.51716736
[nan nan nan nan nan]
[nan nan nan nan nan] 0.0 1.0
[       nan        nan 0.51716736        nan        nan]

0.4609964
[       nan        nan 0.51716736        nan        nan]
[nan nan] 0.0 0.51716736
[       nan 0.4609964  0.51716736        nan        nan]

0.04710595
[       nan 0.4609964  0.51716736        nan        nan]
[nan] 0.0 0.4609964
[0.04710595 0.4609964  0.51716736        nan        nan]

0.5313387
[0.04710595 0.4609964  0.51716736        nan        nan]
[nan nan] 0.51716736 1.0
[0.04710595 0.4609964  0.51716736 0.5313387         nan]

0.84448939
[0.04710595 0.4609964  0.51716736 0.5313387         nan]
[nan] 0.5313387 1.0
[0.04710595 0.4609964  0.51716736 0.5313387  0.84448939]


array([0.04710595, 0.4609964 , 0.51716736, 0.5313387 , 0.84448939])

In [83]:
l = []
trials = 500
sorti = InfinitesimalSort()
thresholds = {i: sorti.thresholds(i)[1]  for i in range(10)}
for i in range(trials):
    try:
        l.append(best_quasi_sort(my_random[i], thresholds))
        print('Sortable')
        print(my_random[i])
    except:
        pass


Sortable
[0.51716736 0.4609964  0.04710595 0.5013387  0.04448939]


In [84]:
l

[array([0.        , 0.04448939, 0.5013387 , 0.        , 0.        ])]