In [18]:
import os
os.chdir(os.path.dirname('/home/pablo/Documents/code/jupyter'))
from src.my_sort import InfinitesimalSort, return_subarray, index_from_thresholds
import numpy as np
optimal = InfinitesimalSort()
import ipytest
ipytest.autoconfig()
nan = np.nan

In [65]:
def best_quasi_sort(arr: np.array, thresholds = None):
    ''' Uses thresholds to sort the array into slots, if slot occupied,'''
    # if not isinstance(np.array, arr):
    n = len(arr)
    slots = np.tile(nan,n)
    if thresholds is None:
        sorti = InfinitesimalSort()
        thresholds = {i: sorti.thresholds(i)[1]  for i in range(n+1)}
    
    for i, ni in enumerate(arr):
        print()
        print(ni)
        print(slots)
        sub, start, end = return_subarray(slots, ni)
        print(sub, start, end)
        if len(sub) == 0:
            print('not best')
            print(slots[np.isnan(slots)])
            slots[np.isnan(slots)] = best_quasi_sort(arr[i:], thresholds = thresholds)
            #raise ValueError('No subarray found, not optimally sortable')
        else:
            nip = (ni-start)/(end-start)     
            # print("thershold: ",thresholds[len(sub)], nip)
            idx = index_from_thresholds(thresholds[len(sub)], nip)
            sub[idx] = ni
            print(slots)
    return slots


In [66]:
a = np.array([0.1406, 0.4243, 0.967, 0.534])
best_quasi_sort(a)


0.1406
[nan nan nan nan]
[nan nan nan nan] 0.0 1.0
[0.1406    nan    nan    nan]

0.4243
[0.1406    nan    nan    nan]
[nan nan nan] 0.1406 1.0
[0.1406    nan 0.4243    nan]

0.967
[0.1406    nan 0.4243    nan]
[nan] 0.4243 1.0
[0.1406    nan 0.4243 0.967 ]

0.534
[0.1406    nan 0.4243 0.967 ]
[] 0.4243 0.967
not best
[nan]

0.534
[nan]
[nan] 0.0 1.0
[0.534]


array([0.1406, 0.534 , 0.4243, 0.967 ])

In [7]:
l = []
trials = 30
n = 5
sorti = InfinitesimalSort()
thresholds = {i: sorti.thresholds(i)[1]  for i in range(10)}
arrays = np.random.uniform(0,1,(trials, n))
for i, random in enumerate(arrays):
    try:
        a = best_quasi_sort(random, thresholds)
        print('Sortable')
        l.append(a)
        print(a)
    except:
        pass

print(optimal.mP(5))
print(len(l)/trials)

Sortable
[0.11433702 0.53456103 0.66129611 0.69312266 0.91822177]
Sortable
[0.19513702 0.23331841 0.30793616 0.41538119 0.67537636]
Sortable
[0.02552507 0.20679271 0.25494702 0.64505085 0.67539488]
Sortable
[0.0506458  0.32372463 0.39309923 0.70841613 0.82063148]
Sortable
[0.0786254  0.25410321 0.42851061 0.48806581 0.67306825]
Sortable
[0.09227421 0.18283463 0.65054908 0.66176032 0.77802125]
Sortable
[0.01089187 0.3653648  0.52763723 0.73630928 0.98351881]
Sortable
[0.16348976 0.60105154 0.6567878  0.77825897 0.99103866]
Sortable
[7.17007012e-04 2.21772913e-01 7.12314525e-01 7.23965571e-01
 9.86857384e-01]
Sortable
[0.07129022 0.37975689 0.64809605 0.67192375 0.76465317]
0.221406029897821
0.3333333333333333


In [64]:
return_subarray([nan], 0.2)

([nan], 0.0, 1.0)